apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce-ns
type: Opaque
data:
  # Les valeurs doivent être encodées en base64
  # echo -n 'root' | base64 => cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: cm9vdA==
  DB_USER: cm9vdA==
  DB_PASS: cm9vdA==